// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_WEB'] ?? 'default',
    appId: dotenv.env['APP_ID_WEB'] ?? 'default',
    messagingSenderId: dotenv.env['MESSAGE_SENDER_ID'] ?? 'default',
    projectId: dotenv.env['PROJECT_ID'] ?? 'default',
    authDomain: dotenv.env['AUTH_DOMAIN'] ?? 'default',
    databaseURL: dotenv.env['DATABASE_URL'] ?? 'default',
    storageBucket: dotenv.env['STORAGE_BUCKED'] ?? 'default',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY_ANDROID'] ?? 'default',
    appId: dotenv.env['API_ID_ANDROID'] ?? 'default',
    messagingSenderId: dotenv.env['MESSAGE_SENDER_ID'] ?? 'default',
    projectId: dotenv.env['PROJECT_ID'] ?? 'default',
    databaseURL: dotenv.env['DATABASE_URL'] ?? 'default',
    storageBucket: dotenv.env['STORAGE_BUCKED'] ?? 'default',
  );

}